
        $(function($){
            $(".zoom_vtech").click(function(){
                $(".detail:nth-of-type(1)").css("display","block");
                $(".close").click(function(){
                    $(".detail").css("display","none");
                });
            });
        });
        $(function($){
            $(".zoom_olpark").click(function(){
                $(".detail:nth-of-type(2)").css("display","block");
                $(".close").click(function(){
                    $(".detail").css("display","none");
                });
            });
        });
        $(function($){
            $(".zoom_bookstore").click(function(){
                $(".detail:nth-of-type(3)").css("display","block");
                $(".close").click(function(){
                    $(".detail").css("display","none");
                });
            });
        });
        $(function($){
            $(".zoom_physiogel").click(function(){
                $(".detail:nth-of-type(4)").css("display","block");
                $(".close").click(function(){
                    $(".detail").css("display","none");
                });
            });
        });
        $(function($){
            $(".zoom_socialcommerce").click(function(){
                $(".detail:nth-of-type(5)").css("display","block");
                $(".close").click(function(){
                    $(".detail").css("display","none");
                });
            });
        });
        $(function($){
            $(".zoom_travel").click(function(){
                $(".detail:nth-of-type(6)").css("display","block");
                $(".close").click(function(){
                    $(".detail").css("display","none");
                });
            });
        });
        $(function($){
            $(".zoom_arthall").click(function(){
                $(".detail:nth-of-type(7)").css("display","block");
                $(".close").click(function(){
                    $(".detail").css("display","none");
                });
            });
        });
        $(function($){
            $(".zoom_kairosoft").click(function(){
                $(".detail:nth-of-type(8)").css("display","block");
                $(".close").click(function(){
                    $(".detail").css("display","none");
                });
            });
        });
        $(function($){
            $(".zoom_keyboard").click(function(){
                $(".detail:nth-of-type(9)").css("display","block");
                $(".close").click(function(){
                    $(".detail").css("display","none");
                });
            });
        });
        $(function($){
            $(".zoom_physiogelposter").click(function(){
                $(".detail:nth-of-type(10)").css("display","block");
                $(".close").click(function(){
                    $(".detail").css("display","none");
                });
            });
        });